[General] Update setup script to manage multiple years.

diff --git a/setup-day b/setup-day
--- a/setup-day
+++ b/setup-day
@@ -1,19 +1,19 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
-# Copied from BurntSushis version in
-# https://github.com/BurntSushi/advent-of-code/blob/93fc69250fb14ce30fee1bdc39daa4109797dfd2/setup-day
+# Based on BurntSushis version available at https://github.com/BurntSushi/advent-of-code/blob/master/setup-day
 
-YEAR=2018
-
-if [ $# != 1 ]; then
-    echo "Usage: $(basename "$0") <day-number>" >&2
+if [ "$#" != 2 ]; then
+    echo "Usage: $(basename "$0") <year> <day-number>" >&2
     exit 1
 fi
+
 if [ ! -d .git ]; then
-    echo "must be run from root of advent-of-code repository" >&2
+    echo "Error: must be run from root of advent-of-code repository" >&2
     exit 1
 fi
 
-name="$(printf "aoc%02d" "$1")"
-cargo new --bin "$YEAR/$name"
-mkdir "$YEAR/$name/input"
+YEAR="${1}"
+DAY="$(printf "%02d" "${2}")"
+
+cargo new --bin "${YEAR}/${DAY}" --name "aoc_${YEAR}_${DAY}"
+mkdir -p "${YEAR}/${DAY}/input"
